config/routes.rb
TwoTierDefinitionx::Engine.routes.draw do
  resources :definitions
  resources :sub_definitions
  root :to => 'definitions#index'
end

app/models/two_tier_definitionx/definition.rb
module TwoTierDefinitionx
  class Definition < ActiveRecord::Base
    attr_accessor :active_noupdate

    belongs_to :last_updated_by, :class_name => 'Authentify::User'
    has_many :sub_definitions, :class_name => 'TwoTierDefinitionx::SubDefinition'
    accepts_nested_attributes_for :sub_definitions, :allow_destroy => true
    
    validates :for_which, :fort_token, :presence => true
    validates :name, :presence => true,
                     :uniqueness => {:scope => [:for_which, :fort_token], :case_sensitive => false, :message => I18n.t('Duplicate Name!')}
    validate :dynamic_validate 
    
    default_scope {where(fort_token: Thread.current[:fort_token])}
    
    def dynamic_validate
      wf = Authentify::AuthentifyUtility.find_config_const('dynamic_validate_definition', self.fort_token, 'two_tier_definitionx')
      eval(wf) if wf.present?
    end   
  end
end

app/models/two_tier_definitionx/sub_definition.rb
module TwoTierDefinitionx
  class SubDefinition < ActiveRecord::Base
    attr_accessor :active_noupdate


    belongs_to :definition, :class_name => 'TwoTierDefinitionx::Definition'
    
    validates :name, :presence => true,
                     :uniqueness => {:scope => :definition_id, :case_sensitive => false, :message => I18n.t('Duplicate Name!')}
    validates :fort_token, :presence => true
    validate :dynamic_validate 
    
    default_scope {where(fort_token: Thread.current[:fort_token])}
    
    def dynamic_validate
      wf = Authentify::AuthentifyUtility.find_config_const('dynamic_validate_sub_definition', self.fort_token, 'two_tier_definitionx')
      eval(wf) if wf.present?
    end   
  end
end

app/controllers/two_tier_definitionx/application_controller.rb
module TwoTierDefinitionx
  class ApplicationController < ::ApplicationController
    include Authentify::SessionsHelper
    include Authentify::AuthentifyUtility
    include Authentify::UsersHelper
    include Authentify::UserPrivilegeHelper
    include Commonx::CommonxHelper
    
    before_action :require_signin
    before_action :max_pagination 
    before_action :check_access_right 
    before_action :load_session_variable, :only => [:new, :edit]  #for parent_record_id & parent_resource in check_access_right
    after_action :delete_session_variable, :only => [:create, :update]   #for parent_record_id & parent_resource in check_access_right
    
    helper_method :has_action_right?
    
    protected
  
    def max_pagination
      @max_pagination = find_config_const('pagination', session[:fort_token]).to_i
    end
    
  end
end

app/controllers/two_tier_definitionx/definitions_controller.rb
require_dependency "two_tier_definitionx/application_controller"

module TwoTierDefinitionx
  class DefinitionsController < ApplicationController
    #before_filter :require_employee
    before_filter :load_for_which, :only => [:index, :new, :edit, :show] 
    after_action :info_logger, :except => [:new, :edit, :event_action_result, :wf_edit_result, :search_results, :stats_results, :acct_summary_result]
    
    def index
      @title = t(@for_which.sub('_', ' ').pluralize.titleize)  #ex, Quality Systems
      @definitions = params[:two_tier_definitionx_definitions][:model_ar_r]
      @definitions = @definitions.where(:for_which => @for_which)
      @definitions = @definitions.page(params[:page]).per_page(@max_pagination).order('ranking_index')
      @erb_code = find_config_const('definition_index_view', session[:fort_token], 'two_tier_definitionx')     
    end
  
    def new
      @title = t("New " + @for_which.sub('_', ' ').titleize)  #ex, New Quality System
      @definition = TwoTierDefinitionx::Definition.new()
      @definition.sub_definitions.build
      @erb_code = find_config_const('definition_new_view', session[:fort_token], 'two_tier_definitionx')  
      @erb_code_field = find_config_const('definition_new_view_field', session[:fort_token], 'two_tier_definitionx') 
    end
  
    def create
      @definition = TwoTierDefinitionx::Definition.new(new_params)
      @definition.fort_token = session[:fort_token]
      @definition.last_updated_by_id = session[:user_id]
      fill_in_token()
      if @definition.save
        redirect_to definitions_path(:for_which => @definition.for_which, :subaction => @definition.for_which), :notice => t("Definition Saved!")
      else
        @for_which = params[:definition][:for_which]
        @erb_code = find_config_const('definition_new_view', session[:fort_token], 'two_tier_definitionx')  
        @erb_code_field = find_config_const('definition_new_view_field', session[:fort_token], 'two_tier_definitionx') 
        flash.now[:error] = t('Data Error. Not Saved!')
        render 'new'
      end
    end
  
    def edit
      @title = t("Update " + @for_which.sub('_', ' ').titleize)
      @definition = TwoTierDefinitionx::Definition.find(params[:id])
      @erb_code = find_config_const('definition_edit_view', session[:fort_token], 'two_tier_definitionx')  
      @erb_code_field = find_config_const('definition_new_view_field', session[:fort_token], 'two_tier_definitionx') 
    end
  
    def update
      @definition = TwoTierDefinitionx::Definition.find(params[:id])
      @definition.last_updated_by_id = session[:user_id]
      if @definition.update_attributes(edit_params)
        redirect_to definitions_path(:for_which => @definition.for_which, :subaction => @definition.for_which), :notice => t("Definition Updated!")
      else
        @for_which = TwoTierDefinitionx::Definition.find(params[:id]).for_which
        @erb_code = find_config_const('definition_update_view', session[:fort_token], 'two_tier_definitionx')  
        @erb_code_field = find_config_const('definition_new_view_field', session[:fort_token], 'two_tier_definitionx')   
        flash.now[:error] = t('Data Error. Not Updated!')
        render 'edit'
      end
    end
    
    def show
      @title = t(@for_which.sub('_', ' ').titleize + ' Info')
      @definition = TwoTierDefinitionx::Definition.find(params[:id])
      @erb_code = find_config_const('definition_show_view', session[:fort_token], 'two_tier_definitionx')  
    end
  
    protected
    
    def load_for_which     
      @for_which = params[:for_which].strip if params[:for_which].present?
      @for_which = TwoTierDefinitionx::Definition.find_by_id(params[:id]).for_which if params[:id].present?
      if @for_which.blank?
        redirect_to URI.escape(SUBURI + "/view_handler?index=0&msg=NO Subaction in Definition!") 
      end
    end
    
    def fill_in_token
      @definition.sub_definitions.each do |r|
        r.fort_token = session[:fort_token]
      end
    end
    
    private
    
    def new_params
      params.require(:definition).permit(:active, :brief_note, :for_which, :last_updated_by_id, :name, :ranking_index, 
                                         :sub_definitions_attributes => [:name, :ranking_index, :brief_note, :id, :_destroy])
    end
    
    def edit_params
      params.require(:definition).permit(:active, :brief_note, :for_which, :last_updated_by_id, :name, :ranking_index, 
                                         :sub_definitions_attributes => [:name, :ranking_index, :active, :brief_note, :id, :_destroy])
    end
  end
end

app/controllers/two_tier_definitionx/sub_definitions_controller.rb
require_dependency "two_tier_definitionx/application_controller"

module TwoTierDefinitionx
  class SubDefinitionsController < ApplicationController
    protect_from_forgery with: :exception, except: [:new, :edit]
    before_filter :load_record
    after_action :info_logger, :except => [:new, :edit, :event_action_result, :wf_edit_result, :search_results, :stats_results, :acct_summary_result]
    
    def index
      @title = I18n.t(@definition.for_which.titleize) + ' - ' + I18n.t('Sub Definitions') #ex, Quality System - Sub Definitions
      @sub_definitions = params[:two_tier_definitionx_sub_definitions][:model_ar_r]
      @sub_definitions = @definition.sub_definitions if @definition
      @sub_definitions = @sub_definitions.page(params[:page]).per_page(@max_pagination).order('ranking_index')  
      @erb_code = find_config_const('sub_definition_index_view', session[:fort_token], 'two_tier_definitionx')     
    end
    
    def new
      @sub_definition = TwoTierDefinitionx::SubDefinition.new()
    end
    
    def create
      @sub_definition = TwoTierDefinitionx::SubDefinition.new(new_params)
      #@sub_definition.last_updated_by_id = session[:user_id]
      @sub_definition.fort_token = session[:fort_token] 
      if @sub_definition.save
        redirect_to sub_definitions_path(:definition_id => @sub_definition.definition_id, :subaction => @sub_definition.definition.for_which), :notice => t("Definition Saved!")
      else
        @definition = TwoTierDefinitionx::Definition.find_by_id(@sub_definition.definition_id)
        flash.now[:error] = t('Data Error. Not Saved!')
        render 'new'
      end
    end
    
    def edit
      @sub_definition = TwoTierDefinitionx::SubDefinition.find_by_id(params[:id])
    end
    
    def update
      @sub_definition = TwoTierDefinitionx::SubDefinition.find_by_id(params[:id])
      #@sub_definition.last_updated_by_id = session[:user_id]
      if @sub_definition.update_attributes(edit_params)
        redirect_to sub_definitions_path(:definition_id => @sub_definition.definition_id, :subaction => @sub_definition.definition.for_which), :notice => t("Definition Updated!")
      else
        flash.now[:error] = t('Data Error. Not Updated!')
        render 'edit'
      end
    end
    
    protected
    def load_record
      @definition = TwoTierDefinitionx::Definition.find_by_id(params[:definition_id]) if params[:definition_id].present?
    end
    
    private
    
    def new_params
      params.require(:sub_definition).permit(:active, :brief_note, :definition_id, :name, :ranking_index)
    end
    
    def edit_params
      params.require(:sub_definition).permit(:active, :brief_note, :name, :ranking_index)
    end
    
  end
end

app/helpers/two_tier_definitionx/application_helper.rb
module TwoTierDefinitionx
  module ApplicationHelper
  end
end

app/helpers/two_tier_definitionx/definitions_helper.rb
module TwoTierDefinitionx
  module DefinitionsHelper
  end
end

app/helpers/two_tier_definitionx/sub_definitions_helper.rb
module TwoTierDefinitionx
  module SubDefinitionsHelper
  end
end

app/views/two_tier_definitionx/sub_definitions/_form_list.html.erb
<% if  @erb_code %>
  <%= render inline: ERB.new(@erb_code).result(binding) %>
  
<% else %>

<h4><%=@title %></h4>
  <table class="table table-striped">
    <tr>
      <th><%= t('Create Date') %></th>
      <th><%= t('Brief Note') %></th>
      <th><%= t('Ranking Index') %></th>
      <th><%= t('Active') %></th>
      <th></th>
    </tr>

    <% models.each do |qs| %>
        <tr>
          <td><%= (qs.created_at + H_FROM_GMT.hours).strftime("%Y/%m/%d")%></td>
          <td><%= link_to qs.name, definition_path(qs) %></td>
          <td><%= qs.brief_note %></td>
          <td><%= qs.ranking_index %></td>
          <td><%= qs.active ? t('Yes') : t('No') %></td>
          <td><%= link_to t('Edit'), edit_sub_definition_path(qs, :subaction => session[:subaction], :definition_id => qs.definition_id, format: :js), 
                  remote: true, :class => BUTTONS_CLS['action'] if has_action_right?('update_' + @definition.for_which, 'two_tier_definitionx/definitions', qs) %></td>
        </tr>
    <% end %>

  </table>

	<table class="table table-striped">
	  <tr>
	    <th>
	    	<%= link_to t('Back'), SUBURI + "/view_handler?index=0", :id => 'close', :class => BUTTONS_CLS['action'] %>
	    	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
	    	<%= link_to t("New Sub Category"), new_sub_definition_path(:definition_id => @definition.id, subaction: @definition.for_which, :format => :js), :remote => true, id: 'new_sub', :class => BUTTONS_CLS['action'] if @definition && has_action_right?('create_' + @definition.for_which, 'two_tier_definitionx/definitions') %>   
		</th>
	  </tr>
	</table>

<% end %>	

app/views/two_tier_definitionx/sub_definitions/edit.html.erb
<%= simple_form_for @sub_definition, html: { class: 'form-horizontal col-sm-' + BUTTONS_CLS['form-span#'] },
    wrapper: :horizontal_form,
    wrapper_mappings: {
    check_boxes: :horizontal_radio_and_checkboxes,
    radio_buttons: :horizontal_radio_and_checkboxes,
    file: :horizontal_file_input,
    boolean: :horizontal_boolean
  } do |f| %>
  
  <div class="form-inputs"> 
  	<%= f.input :name, :label => t('Name') %>
    <%= f.input :active, :label => t("Active"), :collection => [[t('Yes'), true], [t('No'), false]] %>
    <%= f.input :ranking_index, :label => t("Ranking Index") %> 
    <%= f.input :brief_note, :label => t("Brief Note")%>
    
    <div class="btn-toolbar" >
      <%= link_to t('Back'), sub_definitions_path(definition_id: @definition.id, subaction: @definition.for_which), :class => BUTTONS_CLS['action'] %>   
      <%= f.button :submit, I18n.t('Save'), :class => BUTTONS_CLS['action'] %>  
    </div>     
    
  </div>
 
<% end %>

app/views/two_tier_definitionx/sub_definitions/edit.js.erb
$("<%= escape_javascript render(:file => 'two_tier_definitionx/sub_definitions/new.html.erb') %>").insertAfter('#new_sub');
$('#new_sub').hide();
$('#close').hide();

app/views/two_tier_definitionx/sub_definitions/index.html.erb
 
	<%= render partial: 'form_list', locals: {models: @sub_definitions} %>
 

app/views/two_tier_definitionx/sub_definitions/new.html.erb
<%= simple_form_for @sub_definition, html: { class: 'form-horizontal col-sm-' + BUTTONS_CLS['form-span#'] },
    wrapper: :horizontal_form,
    wrapper_mappings: {
    check_boxes: :horizontal_radio_and_checkboxes,
    radio_buttons: :horizontal_radio_and_checkboxes,
    file: :horizontal_file_input,
    boolean: :horizontal_boolean
  } do |f| %>
  
  <div class="form-inputs"> 
  	<%= f.input :name, :label => t('Name') %>
    <%= f.input :active, :as => :hidden, input_html: {value: true} %>
    <%= f.input :ranking_index, :label => t("Ranking Index") %> 
    <%= f.input :brief_note, :label => t("Brief Note")%>
    <%= f.input :definition_id, required: true, as: :hidden, input_html: {value: @definition.id}%>
  
    <div class="btn-toolbar" >
      <%= link_to t('Back'), sub_definitions_path(definition_id: @definition.id, subaction: @definition.for_which), :class => BUTTONS_CLS['action'] %>   
      <%= f.button :submit, I18n.t('Save'), :class => BUTTONS_CLS['action'] %>  
    </div>     
    
  </div>
 
<% end %>

app/views/two_tier_definitionx/sub_definitions/new.js.erb
$("<%= escape_javascript render(:file => 'two_tier_definitionx/sub_definitions/new.html.erb') %>").insertAfter('#new_sub');
$('#new_sub').hide();
$('#close').hide();